---
- name: 加载iptables参数信息
  include_vars:
    file: "{{initialize_type}}.yml"
- name: 停止iptables服务
  shell: /etc/init.d/iptables stop
- name: 设置iptables INPUT 允许访问的节点
  iptables:
    chain: INPUT
    source: "{{ item }}"
    jump: ACCEPT
  with_items:
    "{{ allow_nodes }}"
  when: allow_nodes is defined and allow_nodes
- name: 允许已连接节点保持连接状态
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
- name: 禁止部分协议
  iptables:
    chain: INPUT
    protocol: "{{ item }}"
    reject_with: icmp-host-prohibited
  with_items:
    "{{drop_protocol}}"
- name: 设置表的默认规则
  iptables:
    chain: "{{ item.chain }}"
    policy: "{{ item.policy }}"
  with_items:
    "{{chian_rules}}"
- name: 保存iptables 规则
  shell: /etc/init.d/iptables save