---
- name: "确认使用iptables"
  import_tasks: iptables.yml
  when: ansible_distribution_major_version == "6"
- name: "确认使用firewalld"
  import_tasks: firewalld.yml
  when: ansible_distribution_major_version == "7"